### ISSUE TITLE
Missing Training and Testing Code

### ISSUE THREAD

**Issue by Johnson-jelly** [sunhan1997/PanelPose#1]
Thank you very much for sharing this project! I find it very interesting and valuable.  
After reviewing the `README.md` and the provided code, I noticed that the repository does not seem to include training or testing-related code or instructions.  

I have a few specific questions:  
1. Are there any additional documents or guidelines available to help reproduce the training and testing process?  
2. If possible, could you kindly provide some brief instructions to help better utilize your code?  
3. For the data generation part, only the generated pose files are saved. What image data should be saved?

Thanks

**Comment by sunhan1997** [comment]
I am very honor for your interest in this repository.



1. This work is done in cooperation with a company, so we are very sorry that we cannot provide relevant complete codes for training and testing.


2. We are very sorry that the code instructions are too simple, because we are always busy completing the boss's business project. In fact, we were only allowed to open source the keypoint selection method and the data generation method at first. mult_scale_icp.py and networks.py are universal, which is why the company agreed to open source. This project uses OpenGL to render and capture key point data. On https://github.com/sunhan1997/PanelPose/blob/ba580bff57a463f4bd9a11630219d072db04aeb6/tools/creat_RT.py#L182  , We render depth and rgb images, you can save these images as data, or change the background to achieve domain randomization. You can also use https://github.com/sunhan1997/PanelPose/blob/master/tools/dataset_edge_kps_tools/gen_obj_info.py  to sample keypoint. You can use https://github.com/sunhan1997/PanelPose/blob/ba580bff57a463f4bd9a11630219d072db04aeb6/tools/dataset_edge_kps_tools/gen_obj_info.py#L18 to change your mesh. 


3. Actually, this  method is too old. More recently, some zero shot pose estimation methods (such as FoundationPose) have been able to achieve better results, and the FoundationPose can achieve 6D pose estimation and 6D pose track. In addition,  I think the 6D pose estimation task has become difficult to do new work. 


If you have any questions about 6D pose estimation, please feel free to communicate.


| |
孙晗
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/3/2024 23:17 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [sunhan1997/PanelPose] Missing Training and Testing Code (Issue #1) |

Thank you very much for sharing this project! I find it very interesting and valuable.
After reviewing the README.md and the provided code, I noticed that the repository does not seem to include training or testing-related code or instructions.

I have a few specific questions:

Are there any additional documents or guidelines available to help reproduce the training and testing process?
If possible, could you kindly provide some brief instructions to help better utilize your code?
For the data generation part, only the generated pose files are saved. What image data should be saved?

Thanks
